### ISSUE TITLE
relishapp.com/rspec throws 500

### ISSUE THREAD

**Issue by dmke** [rspec/relish-root-repo#5]
Not sure if you are able to fix it, but https://relishapp.com/rspec/ does not render anymore:

![image](https://user-images.githubusercontent.com/327411/208615818-50f5b81e-9935-4b1f-b56a-1f0851a17183.png)

I can access the Gem sub-sites (like https://relishapp.com/rspec/rspec-core/docs) without issue.

IIRC, the root page did still work in 2022W49 or W50.

**Comment by pirj** [comment]
@mattwynne can you please have a look?

**Comment by JonRowe** [comment]
Closing because relishapp.com is not under our control.

**Comment by dmke** [comment]
> relishapp.com is not under our control

Thought so, but still wanted to let you know.

**Comment by mattwynne** [comment]
Gah sorry folks, this app has been running for years with no maintenance, I'm not sure what's up with it.

**Comment by mattwynne** [comment]
Are you still relying on it? Do you need me to look into it?

You can come find me in the https://cucumber.io/community#slack if you want to chat, or book a slot with me [here](https://calendly.com/mattwynne).

**Comment by dmke** [comment]
> Are you still relying on it?

Not often, but every now and then I come across some thinly documented piece of RSpec code (in terms of Yardoc). In the past I could rely on the search on relishapp.com/rspec to find out more about that code.

I do also need to lookup the documentation for specific (read: ancient) versions, because of, well legacy apps in dire need of upgrades :)

> Do you need me to look into it?

As a end-user, I'd like to see it fixed.

Alternatively, I can host those docs by myself - but I don't use Cucumber, so I don't know how and where to start. I assume relishapp.com hosts a bunch of static files, and "just" provides a search index around it, no?

**Comment by pirj** [comment]
Thanks a lot @mattwynne !
We paired and managed to fix http://relishapp.com/rspec/

**Comment by dmke** [comment]
Can confirm, thank you very much!

**Comment by ydah** [comment]
@pirj Very sad, but ~it seems to be happening again~ there seems to be an error of some sort that is different.
https://relishapp.com/rspec/

**Comment by JonRowe** [comment]
This seems to be an error in general for Relish, not specific to us.

**Comment by benoittgt** [comment]
@JonRowe Do we want to look for alternative?

At the moment we [do not know](https://twitter.com/mattwynne/status/1630438199519756289) if it will be working again one day. Maybe @tooky knows?

We may have a look again on https://github.com/rspec/rspec-dev/issues/199 also some suggestions on VCR gems https://github.com/vcr/vcr/issues/755

Sorry to hear [what happen](https://mattwynne.net/new-beginning) @mattwynne ✊

**Comment by benoittgt** [comment]
Some work started [here](https://github.com/vcr/vcr/issues/967) for VCR, but it will be very similar for RSpec.

**Comment by JonRowe** [comment]
I'm working on putting the features into our docs, I'd rather self host to be more maintainable in future.
